project:
  type: website
  output-dir: docs
    resources:
    - projectex/**
  
website:
  title: "Abigail Balint's DACSS 604 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/abigailbalint
      - icon: github
        href: https://github.com/abbybalint/AbbyBalint_DACSS604_Fall2025
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Abigail Balint"

format:
  html:
    theme: cerulean
    toc: true

editor: source